import { BookingLead, QuoteLead, ChatConversation, CleanerSpecialist } from "@/lib/types";
import { CLEANING_SPECIALISTS } from "@/lib/constants/riverside-data";

export const INITIAL_BOOKINGS: BookingLead[] = [
  {
    id: "bk-901",
    bookingReference: "MM-RIV-8942",
    customerName: "Eleanor Vance",
    customerEmail: "eleanor.vance@gmail.com",
    customerPhone: "(951) 342-8819",
    serviceId: "srv-deep",
    serviceTitle: "Luxury Deep Clean",
    squareFootage: 2800,
    bedrooms: 4,
    bathrooms: 3,
    halfBathrooms: 1,
    addOns: [
      { slug: "inside-oven", name: "Inside Oven Scour", price: 45 },
      { slug: "baseboards-doors", name: "Baseboards & Door Frames", price: 50 },
    ],
    frequency: "bi_weekly",
    frequencyDiscountPercent: 15,
    subtotal: 398.0,
    discountAmount: 59.7,
    finalTotal: 338.3,
    serviceDate: "2026-09-27",
    serviceTimeSlot: "Morning (8:00 AM - 11:00 AM)",
    addressLine1: "4820 Overlook Terrace",
    city: "Riverside",
    state: "CA",
    zipCode: "92506",
    neighborhood: "Canyon Crest",
    entryInstructions: "Gate code #4492. Key lockbox on side porch under potted fern.",
    specialNotes: "Please pay special attention to master bath marble and steam shower.",
    status: "confirmed",
    cleanerId: "cl-1",
    assignedCleaner: CLEANING_SPECIALISTS[0],
    createdAt: "2026-09-24T14:30:00Z",
    updatedAt: "2026-09-24T15:00:00Z",
  },
  {
    id: "bk-902",
    bookingReference: "MM-RIV-8943",
    customerName: "Gregory Miller",
    customerEmail: "gmiller.realty@outlook.com",
    customerPhone: "(951) 529-1044",
    serviceId: "srv-move",
    serviceTitle: "Move-In / Move-Out Turnover",
    squareFootage: 3400,
    bedrooms: 5,
    bathrooms: 4,
    halfBathrooms: 0,
    addOns: [
      { slug: "inside-fridge", name: "Inside Fridge & Freezer", price: 40 },
      { slug: "inside-cabinets", name: "Inside Cabinets & Drawers", price: 45 },
      { slug: "interior-windows", name: "Interior Windows & Tracks", price: 55 },
    ],
    frequency: "one_time",
    frequencyDiscountPercent: 0,
    subtotal: 512.0,
    discountAmount: 0,
    finalTotal: 512.0,
    serviceDate: "2026-09-28",
    serviceTimeSlot: "Midday (11:00 AM - 2:00 PM)",
    addressLine1: "1892 Citrus Grove Way",
    city: "Riverside",
    state: "CA",
    zipCode: "92508",
    neighborhood: "Orangecrest",
    entryInstructions: "Front door key under welcome mat. Real estate lockbox on gas meter.",
    specialNotes: "Deposit inspection scheduled next day at 10 AM. Needs spotless finish.",
    status: "pending",
    cleanerId: undefined,
    createdAt: "2026-09-24T16:15:00Z",
    updatedAt: "2026-09-24T16:15:00Z",
  },
  {
    id: "bk-903",
    bookingReference: "MM-RIV-8944",
    customerName: "Dr. Amanda Wright",
    customerEmail: "awright.md@ucrhealth.org",
    customerPhone: "(951) 827-3920",
    serviceId: "srv-standard",
    serviceTitle: "Standard Maintenance Clean",
    squareFootage: 1950,
    bedrooms: 3,
    bathrooms: 2,
    halfBathrooms: 0,
    addOns: [
      { slug: "pet-hair-detail", name: "Pet Hair Extraction Detail", price: 35 },
      { slug: "eco-green-supplies", name: "100% Botanical Green Supplies", price: 15 },
    ],
    frequency: "weekly",
    frequencyDiscountPercent: 20,
    subtotal: 246.5,
    discountAmount: 49.3,
    finalTotal: 197.2,
    serviceDate: "2026-09-26",
    serviceTimeSlot: "Morning (8:00 AM - 11:00 AM)",
    addressLine1: "3614 Mission Inn Ave",
    city: "Riverside",
    state: "CA",
    zipCode: "92501",
    neighborhood: "Wood Streets",
    entryInstructions: "Ring Ring doorbell. Golden retriever will be in backyard dog run.",
    specialNotes: "Use plant-based solutions on dark bamboo floors please.",
    status: "dispatched",
    cleanerId: "cl-3",
    assignedCleaner: CLEANING_SPECIALISTS[2],
    createdAt: "2026-09-23T11:00:00Z",
    updatedAt: "2026-09-24T09:00:00Z",
  },
  {
    id: "bk-904",
    bookingReference: "MM-RIV-8945",
    customerName: "Harrison Forde",
    customerEmail: "h.forde@inlandempiremgmt.com",
    customerPhone: "(951) 488-6612",
    serviceId: "srv-airbnb",
    serviceTitle: "Airbnb & Vacation Rental Prep",
    squareFootage: 1400,
    bedrooms: 2,
    bathrooms: 2,
    halfBathrooms: 0,
    addOns: [
      { slug: "interior-windows", name: "Interior Windows & Tracks", price: 55 },
    ],
    frequency: "bi_weekly",
    frequencyDiscountPercent: 15,
    subtotal: 218.0,
    discountAmount: 32.7,
    finalTotal: 185.3,
    serviceDate: "2026-09-25",
    serviceTimeSlot: "Afternoon (2:00 PM - 5:00 PM)",
    addressLine1: "1105 University Ave #204",
    city: "Riverside",
    state: "CA",
    zipCode: "92507",
    neighborhood: "UCR / Box Springs",
    entryInstructions: "Smart lock code 9812#.",
    specialNotes: "Restock coffee pods in kitchen drawer and leave 4 rolled bath towels.",
    status: "in_progress",
    cleanerId: "cl-4",
    assignedCleaner: CLEANING_SPECIALISTS[3],
    createdAt: "2026-09-22T08:45:00Z",
    updatedAt: "2026-09-25T05:00:00Z",
  },
  {
    id: "bk-905",
    bookingReference: "MM-RIV-8940",
    customerName: "Claire & Thomas Sterling",
    customerEmail: "claire.sterling@verizon.net",
    customerPhone: "(951) 682-1490",
    serviceId: "srv-deep",
    serviceTitle: "Luxury Deep Clean",
    squareFootage: 4100,
    bedrooms: 5,
    bathrooms: 5,
    halfBathrooms: 1,
    addOns: [
      { slug: "inside-oven", name: "Inside Oven Scour", price: 45 },
      { slug: "inside-fridge", name: "Inside Fridge & Freezer", price: 40 },
      { slug: "patio-balcony", name: "Patio & Balcony Sweep/Wipe", price: 30 },
    ],
    frequency: "monthly",
    frequencyDiscountPercent: 10,
    subtotal: 589.0,
    discountAmount: 58.9,
    finalTotal: 530.1,
    serviceDate: "2026-09-23",
    serviceTimeSlot: "Morning (8:00 AM - 11:00 AM)",
    addressLine1: "2195 Victoria Ave",
    city: "Riverside",
    state: "CA",
    zipCode: "92506",
    neighborhood: "Victoria Avenue",
    entryInstructions: "Main iron gate remains open. Ring bell or call cell.",
    specialNotes: "Exceptional job done! Left 5-star Google review.",
    status: "completed",
    cleanerId: "cl-2",
    assignedCleaner: CLEANING_SPECIALISTS[1],
    createdAt: "2026-09-20T10:00:00Z",
    updatedAt: "2026-09-23T16:00:00Z",
  },
];

export const INITIAL_QUOTES: QuoteLead[] = [
  {
    id: "qt-101",
    customerName: "Jessica Reynolds",
    customerEmail: "jessica.rey@gmail.com",
    customerPhone: "(951) 402-9112",
    squareFootage: 2600,
    bedrooms: 4,
    bathrooms: 3,
    serviceType: "Luxury Deep Clean",
    frequency: "bi_weekly",
    addOns: ["inside-oven", "pet-hair-detail"],
    estimatedPrice: 345.0,
    zipCode: "92506",
    neighborhood: "Hawarden Hills",
    status: "abandoned",
    recoveryEmailSent: true,
    recoverySmsSent: false,
    createdAt: "2026-09-24T18:20:00Z",
  },
  {
    id: "qt-102",
    customerName: "Robert Gutierrez",
    customerEmail: "rgutierrez84@yahoo.com",
    customerPhone: "(951) 789-2231",
    squareFootage: 3200,
    bedrooms: 4,
    bathrooms: 3,
    serviceType: "Move-In / Move-Out Turnover",
    frequency: "one_time",
    addOns: ["inside-fridge", "inside-cabinets", "interior-windows"],
    estimatedPrice: 475.0,
    zipCode: "92508",
    neighborhood: "Orangecrest",
    status: "lead_captured",
    recoveryEmailSent: false,
    recoverySmsSent: false,
    createdAt: "2026-09-25T01:10:00Z",
  },
  {
    id: "qt-103",
    customerName: "Nathaniel Black",
    customerEmail: "nblack@blackwoodfirm.com",
    customerPhone: "(951) 640-5590",
    squareFootage: 1800,
    bedrooms: 3,
    bathrooms: 2,
    serviceType: "Standard Maintenance Clean",
    frequency: "weekly",
    addOns: ["eco-green-supplies"],
    estimatedPrice: 185.0,
    zipCode: "92501",
    neighborhood: "Downtown Riverside",
    status: "calculated",
    recoveryEmailSent: false,
    recoverySmsSent: false,
    createdAt: "2026-09-25T03:45:00Z",
  },
];

export const INITIAL_CHAT_CONVERSATIONS: ChatConversation[] = [
  {
    id: "conv-01",
    visitorId: "vis-339",
    visitorName: "Samantha Miller",
    visitorEmail: "samantha.m@gmail.com",
    visitorPhone: "(951) 314-5582",
    status: "open",
    lastMessageAt: "2026-09-25T05:15:00Z",
    createdAt: "2026-09-25T05:00:00Z",
    messages: [
      {
        id: "msg-101",
        conversationId: "conv-01",
        senderType: "visitor",
        senderName: "Samantha Miller",
        message: "Hi! Do I need to provide any vacuum or cleaning supplies for a Move-Out clean in Canyon Crest?",
        isRead: true,
        createdAt: "2026-09-25T05:00:00Z",
      },
      {
        id: "msg-102",
        conversationId: "conv-01",
        senderType: "agent",
        senderName: "MaidsMagic Concierge",
        message: "Hello Samantha! Not at all. Our verified Riverside team brings all commercial-grade HEPA equipment, microfibers, descalers, and hospital-grade eco solutions. All you need to provide is running water & electricity!",
        isRead: true,
        createdAt: "2026-09-25T05:04:00Z",
      },
      {
        id: "msg-103",
        conversationId: "conv-01",
        senderType: "visitor",
        senderName: "Samantha Miller",
        message: "That is wonderful! Can you clean this Saturday at 9:00 AM?",
        isRead: false,
        createdAt: "2026-09-25T05:15:00Z",
      },
    ],
  },
  {
    id: "conv-02",
    visitorId: "vis-340",
    visitorName: "Carlos Benitez",
    visitorEmail: "carlos.b@aol.com",
    visitorPhone: "(951) 890-1244",
    status: "active",
    lastMessageAt: "2026-09-24T22:30:00Z",
    createdAt: "2026-09-24T22:00:00Z",
    messages: [
      {
        id: "msg-201",
        conversationId: "conv-02",
        senderType: "visitor",
        senderName: "Carlos Benitez",
        message: "Do you offer keyless entry cleanings for Airbnb units near UCR campus?",
        isRead: true,
        createdAt: "2026-09-24T22:00:00Z",
      },
      {
        id: "msg-202",
        conversationId: "conv-02",
        senderType: "agent",
        senderName: "Dispatch Team",
        message: "Yes Carlos! We service dozens of Airbnb superhosts around UCR and Box Springs. We use lockbox/smart lock access and send photo verification before checkout inspection.",
        isRead: true,
        createdAt: "2026-09-24T22:10:00Z",
      },
      {
        id: "msg-203",
        conversationId: "conv-02",
        senderType: "visitor",
        senderName: "Carlos Benitez",
        message: "Booking right now using your online quote widget. Thank you!",
        isRead: true,
        createdAt: "2026-09-24T22:30:00Z",
      },
    ],
  },
];
