import { ServiceItem, AddOnItem, ReviewItem, CleanerSpecialist } from "@/lib/types";

export const RIVERSIDE_COMPANY_INFO = {
  name: "MaidsMagic",
  tagline: "The Ultimate Clean for Riverside Homes",
  subheadline: "Luxury residential & commercial white-glove cleaning with verified Riverside specialists.",
  phone: "+1 951-697-9000",
  phoneFormatted: "(951) 697-9000",
  email: "concierge@maidsmagicriverside.com",
  address: "1405 Spruce St, Riverside, CA 92507",
  addressStreet: "1405 Spruce St",
  addressCity: "Riverside",
  addressState: "CA",
  addressZip: "92507",
  addressCountry: "US",
  googleMapsUrl: "https://maps.google.com/?q=1405+Spruce+St,+Riverside,+CA+92507",
  operatingHours: "Monday – Saturday: 7:30 AM – 7:00 PM | Sunday: 8:30 AM – 5:00 PM",
  aggregateRating: {
    ratingValue: 4.96,
    reviewCount: 168,
    bestRating: 5,
    worstRating: 1,
  },
};

export const RIVERSIDE_NEIGHBORHOODS = [
  {
    name: "Canyon Crest",
    zip: "92506 / 92507",
    description: "Hillside estates & luxury country club homes",
    badgeText: "Daily Dedicated Crew",
    popularService: "Luxury Deep Clean",
  },
  {
    name: "Orangecrest",
    zip: "92508",
    description: "Spacious family homes & modern master planned tracts",
    badgeText: "Priority Scheduling",
    popularService: "Bi-Weekly Maintenance",
  },
  {
    name: "Victoria Avenue",
    zip: "92506",
    description: "Historic citrus grove estates & tree-lined avenues",
    badgeText: "Historic Home Specialists",
    popularService: "Luxury Deep Clean",
  },
  {
    name: "Hawarden Hills",
    zip: "92506",
    description: "High-elevation custom estates & panoramic vista homes",
    badgeText: "White-Glove Tier",
    popularService: "Move-In / Move-Out",
  },
  {
    name: "The Wood Streets",
    zip: "92501",
    description: "Beloved 1920s Craftsman bungalows & Spanish Revivals",
    badgeText: "Architectural Care",
    popularService: "Standard Maintenance",
  },
  {
    name: "UCR & Box Springs",
    zip: "92507 / 92521",
    description: "Faculty executive housing & high-turnover rentals",
    badgeText: "Turnover Fast-Track",
    popularService: "Airbnb & Move-Out",
  },
  {
    name: "Mission Grove",
    zip: "92508",
    description: "Foothill gated communities & contemporary executive suites",
    badgeText: "Same-Day Dispatch",
    popularService: "Bi-Weekly Maintenance",
  },
  {
    name: "Downtown Riverside",
    zip: "92501",
    description: "Historic district lofts, townhomes & office suites",
    badgeText: "Flexible Keyless Entry",
    popularService: "Commercial & Residential",
  },
];

export const SERVICES_CATALOG: ServiceItem[] = [
  {
    id: "srv-standard",
    slug: "standard-maintenance",
    title: "Standard Maintenance Clean",
    tagline: "Effortless, sparkling routine upkeep",
    description: "Designed for regularly maintained homes. Full dusting, surface sanitation, vacuuming, mopping, kitchen disinfection, and bathroom scrub.",
    basePrice: 129,
    pricePerSqft: 0.05,
    pricePerBed: 20,
    pricePerBath: 30,
    estimatedHoursBase: 2.5,
    iconName: "Sparkles",
    isActive: true,
  },
  {
    id: "srv-deep",
    slug: "luxury-deep-clean",
    title: "Luxury Deep Clean",
    tagline: "Top-to-bottom restorative rejuvenation",
    description: "An intensive reset scrubbing deep grime, hand-wiping baseboards, polishing cabinet fronts, detail tile grout, fixtures, vents, and door frames.",
    basePrice: 189,
    pricePerSqft: 0.08,
    pricePerBed: 30,
    pricePerBath: 45,
    estimatedHoursBase: 4.0,
    iconName: "ShieldCheck",
    isActive: true,
  },
  {
    id: "srv-move",
    slug: "move-in-move-out",
    title: "Move-In / Move-Out Turnover",
    tagline: "100% Security deposit & inspection guaranteed",
    description: "Empty home white-glove service. Includes interiors of empty cabinets & pantry, baseboards, closet shelving, deep scrub of all surfaces.",
    basePrice: 229,
    pricePerSqft: 0.09,
    pricePerBed: 35,
    pricePerBath: 50,
    estimatedHoursBase: 5.0,
    iconName: "Home",
    isActive: true,
  },
  {
    id: "srv-airbnb",
    slug: "airbnb-turnover",
    title: "Airbnb & Vacation Rental Prep",
    tagline: "5-Star guest review staging in Riverside",
    description: "Fast-turnaround guest turnover. Includes linen changes, laundry, restocking guest amenities, staged bathroom towels, and photo verification.",
    basePrice: 149,
    pricePerSqft: 0.06,
    pricePerBed: 25,
    pricePerBath: 35,
    estimatedHoursBase: 3.0,
    iconName: "BedDouble",
    isActive: true,
  },
  {
    id: "srv-urgent",
    slug: "urgent-same-day",
    title: "Urgent / Same-Day Clean",
    tagline: "Express 2-hour response crew in Riverside",
    description: "Emergency priority dispatch for last-minute guests, unexpected real estate tours, or post-event recovery across Riverside zip codes.",
    basePrice: 219,
    pricePerSqft: 0.09,
    pricePerBed: 35,
    pricePerBath: 50,
    estimatedHoursBase: 3.5,
    iconName: "Zap",
    isActive: true,
  },
];

export const ADDONS_CATALOG: AddOnItem[] = [
  {
    id: "addon-oven",
    slug: "inside-oven",
    name: "Inside Oven Scour",
    description: "Deep carbon & grease degreasing with non-toxic, fume-free formulas",
    price: 45,
    estimatedMinutes: 40,
    iconName: "Flame",
    isActive: true,
  },
  {
    id: "addon-fridge",
    slug: "inside-fridge",
    name: "Inside Fridge & Freezer",
    description: "Shelves washed, sticky spills sanitized, interior walls deodorized",
    price: 40,
    estimatedMinutes: 35,
    iconName: "Refrigerator",
    isActive: true,
  },
  {
    id: "addon-windows",
    slug: "interior-windows",
    name: "Interior Windows & Tracks",
    description: "Streak-free glass cleaning, window sill wiping, and vacuumed tracks",
    price: 55,
    estimatedMinutes: 45,
    iconName: "Maximize2",
    isActive: true,
  },
  {
    id: "addon-pet-hair",
    slug: "pet-hair-detail",
    name: "Pet Hair Extraction Detail",
    description: "Specialized electrostatic roller & HEPA fur extraction for pet lovers",
    price: 35,
    estimatedMinutes: 30,
    iconName: "Dog",
    isActive: true,
  },
  {
    id: "addon-baseboards",
    slug: "baseboards-doors",
    name: "Baseboards & Door Frames",
    description: "Individual hand-wiping of all moldings, baseboards, and interior doors",
    price: 50,
    estimatedMinutes: 45,
    iconName: "Layers",
    isActive: true,
  },
  {
    id: "addon-cabinets",
    slug: "inside-cabinets",
    name: "Inside Cabinets & Drawers",
    description: "Wipe down interior shelves and crumb vacuuming across kitchen & bath",
    price: 45,
    estimatedMinutes: 40,
    iconName: "Archive",
    isActive: true,
  },
  {
    id: "addon-eco",
    slug: "eco-green-supplies",
    name: "100% Botanical Green Supplies",
    description: "Hypoallergenic, plant-based eucalyptus and citrus eco products",
    price: 15,
    estimatedMinutes: 0,
    iconName: "Leaf",
    isActive: true,
  },
  {
    id: "addon-patio",
    slug: "patio-balcony",
    name: "Patio & Balcony Sweep/Wipe",
    description: "Outdoor patio furniture wiping, dust removal, and thorough sweep",
    price: 30,
    estimatedMinutes: 25,
    iconName: "Sun",
    isActive: true,
  },
];

export const VERIFIED_GOOGLE_REVIEWS: ReviewItem[] = [
  {
    id: "rev-1",
    author: "Sarah Jenkins",
    rating: 5,
    date: "3 days ago",
    text: "MaidsMagic transformed our Canyon Crest home! We scheduled the Luxury Deep Clean before hosting family and our kitchen and bathrooms looked brand new. The crew was punctual, masked, and so polite. Truly a luxury experience.",
    neighborhood: "Canyon Crest, Riverside",
    serviceType: "Luxury Deep Clean",
    verifiedSourceUrl: "https://maps.google.com/?q=1405+Spruce+St,+Riverside,+CA+92507",
    avatarUrl: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80",
    isFeatured: true,
  },
  {
    id: "rev-2",
    author: "David Martinez",
    rating: 5,
    date: "1 week ago",
    text: "As a busy real estate agent in Riverside, I need dependable move-out cleaning. MaidsMagic handled three Orangecrest properties for me this month and every single tenant got their full security deposit back. 10/10 service!",
    neighborhood: "Orangecrest, Riverside",
    serviceType: "Move-In/Move-Out",
    verifiedSourceUrl: "https://maps.google.com/?q=1405+Spruce+St,+Riverside,+CA+92507",
    avatarUrl: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80",
    isFeatured: true,
  },
  {
    id: "rev-3",
    author: "Elena Rostova",
    rating: 5,
    date: "2 weeks ago",
    text: "We have two large golden retrievers and dog hair was everywhere. The Pet Hair Detail add-on was magical! Our Hawarden Hills home feels pristine and smells like fresh eucalyptus without harsh chemical fumes.",
    neighborhood: "Hawarden Hills, Riverside",
    serviceType: "Bi-Weekly Maintenance",
    verifiedSourceUrl: "https://maps.google.com/?q=1405+Spruce+St,+Riverside,+CA+92507",
    avatarUrl: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80",
    isFeatured: true,
  },
  {
    id: "rev-4",
    author: "Marcus Vance",
    rating: 5,
    date: "3 weeks ago",
    text: "I run 2 Airbnbs near UCR and Box Springs. MaidsMagic is my secret weapon. They stage towels beautifully, restock essentials, and notify me with photos the minute it is ready. Guests constantly compliment the cleanliness.",
    neighborhood: "UCR / Box Springs, Riverside",
    serviceType: "Airbnb Turnover Prep",
    verifiedSourceUrl: "https://maps.google.com/?q=1405+Spruce+St,+Riverside,+CA+92507",
    avatarUrl: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80",
    isFeatured: true,
  },
  {
    id: "rev-5",
    author: "Patricia & Robert Cole",
    rating: 5,
    date: "1 month ago",
    text: "Living in the historic Wood Streets neighborhood, our crown moldings and 1920s windows require gentle, attentive care. MaidsMagic treats our house with incredible respect. Bi-weekly client for 6 months now!",
    neighborhood: "Wood Streets, Riverside",
    serviceType: "Standard Maintenance",
    verifiedSourceUrl: "https://maps.google.com/?q=1405+Spruce+St,+Riverside,+CA+92507",
    avatarUrl: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80",
    isFeatured: true,
  },
  {
    id: "rev-6",
    author: "Dr. Raymond Chen",
    rating: 5,
    date: "1 month ago",
    text: "Called them at 8:30 AM for an urgent same-day clean in Victoria after our contractor finished tiling. A team of two arrived at 11:00 AM sharp with industrial HEPA vacuums. Impeccable work ethic and fair pricing.",
    neighborhood: "Victoria, Riverside",
    serviceType: "Urgent Same-Day Clean",
    verifiedSourceUrl: "https://maps.google.com/?q=1405+Spruce+St,+Riverside,+CA+92507",
    avatarUrl: "https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=150&auto=format&fit=crop&q=80",
    isFeatured: true,
  },
];

export const CLEANING_SPECIALISTS: CleanerSpecialist[] = [
  {
    id: "cl-1",
    fullName: "Maria Rodriguez",
    teamName: "Emerald Elite Crew Lead",
    phone: "(951) 697-9001",
    email: "maria.r@maidsmagicriverside.com",
    avatarUrl: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80",
    rating: 4.98,
    completedJobs: 412,
    assignedZipCodes: ["92506", "92507", "92508"],
    isActive: true,
  },
  {
    id: "cl-2",
    fullName: "David Sterling",
    teamName: "Gold Standard Deep Clean Crew",
    phone: "(951) 697-9002",
    email: "david.s@maidsmagicriverside.com",
    avatarUrl: "https://images.unsplash.com/photo-1560250097-0b93528c311a?w=150&auto=format&fit=crop&q=80",
    rating: 4.95,
    completedJobs: 320,
    assignedZipCodes: ["92501", "92503", "92504"],
    isActive: true,
  },
  {
    id: "cl-3",
    fullName: "Elena & Carlos Vasquez",
    teamName: "Turnover & Estate Specialist Duo",
    phone: "(951) 697-9003",
    email: "vasquez.team@maidsmagicriverside.com",
    avatarUrl: "https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150&auto=format&fit=crop&q=80",
    rating: 5.0,
    completedJobs: 580,
    assignedZipCodes: ["92506", "92501", "92508", "92507"],
    isActive: true,
  },
  {
    id: "cl-4",
    fullName: "Sofia Gutierrez",
    teamName: "Express & Eco Clean Lead",
    phone: "(951) 697-9004",
    email: "sofia.g@maidsmagicriverside.com",
    avatarUrl: "https://images.unsplash.com/photo-1567532939604-b6b5b0db2604?w=150&auto=format&fit=crop&q=80",
    rating: 4.93,
    completedJobs: 245,
    assignedZipCodes: ["92504", "92505", "92503"],
    isActive: true,
  },
];
