import { ServiceItem, AddOnItem, ReviewItem, CleanerSpecialist, CustomerProfile } from "@/lib/types";

export const RIVERSIDE_COMPANY_INFO = {
  name: "MaidsMagic",
  tagline: "The Ultimate Clean for Riverside Homes",
  subheadline: "Luxury residential & commercial white-glove cleaning with verified Riverside specialists.",
  phone: "+1 951-697-9000",
  phoneFormatted: "(951) 697-9000",
  email: "concierge@maidsmagicriverside.com",
  address: "1405 Spruce St, Riverside, CA 92507",
  addressStreet: "1405 Spruce St",
  addressCity: "Riverside",
  addressState: "CA",
  addressZip: "92507",
  addressCountry: "US",
  googleMapsUrl: "https://maps.google.com/?q=1405+Spruce+St,+Riverside,+CA+92507",
  operatingHours: "Monday – Saturday: 7:30 AM – 7:00 PM | Sunday: 8:30 AM – 5:00 PM",
  aggregateRating: {
    ratingValue: 4.96,
    reviewCount: 168,
    bestRating: 5,
    worstRating: 1,
  },
};

export const RIVERSIDE_NEIGHBORHOODS = [
  {
    name: "Canyon Crest",
    zip: "92506 / 92507",
    description: "Hillside estates & luxury country club homes",
    badgeText: "Daily Dedicated Crew",
    popularService: "Luxury Deep Clean",
  },
  {
    name: "Orangecrest",
    zip: "92508",
    description: "Spacious family homes & modern master planned tracts",
    badgeText: "Priority Scheduling",
    popularService: "Bi-Weekly Maintenance",
  },
  {
    name: "Victoria Avenue",
    zip: "92506",
    description: "Historic citrus grove estates & tree-lined avenues",
    badgeText: "Historic Home Care",
    popularService: "Luxury Deep Clean",
  },
  {
    name: "Hawarden Hills",
    zip: "92506",
    description: "High-elevation custom estates & panoramic vista homes",
    badgeText: "White-Glove Tier",
    popularService: "Move-In / Move-Out",
  },
  {
    name: "The Wood Streets",
    zip: "92501",
    description: "Beloved 1920s Craftsman bungalows & Spanish Revivals",
    badgeText: "Architectural Detail",
    popularService: "Standard Maintenance",
  },
  {
    name: "UCR & Box Springs",
    zip: "92507 / 92521",
    description: "Faculty executive housing & high-turnover rentals",
    badgeText: "Turnover Fast-Track",
    popularService: "Airbnb & Move-Out",
  },
  {
    name: "Mission Grove",
    zip: "92508",
    description: "Foothill gated communities & contemporary executive suites",
    badgeText: "Same-Day Dispatch",
    popularService: "Bi-Weekly Maintenance",
  },
  {
    name: "Downtown Riverside",
    zip: "92501",
    description: "Historic district lofts, townhomes & office suites",
    badgeText: "Keyless Smart Entry",
    popularService: "Commercial & Residential",
  },
];

export const SERVICES_CATALOG: ServiceItem[] = [
  {
    id: "srv-deep",
    slug: "luxury-deep-clean",
    title: "Luxury Deep Clean",
    tagline: "Top-to-bottom restorative reset for pristine living",
    description: "Our signature white-glove reset. Intensive scrub of bathroom tile grout, kitchen degreasing, hand-wiping baseboards, door frames, switch plates, interior vents, and high-touch fixtures.",
    estimatedHoursBase: 4.0,
    iconName: "ShieldCheck",
    badgeText: "Most Requested in Riverside",
    inclusions: [
      "Individual hand-wiping of all baseboards & door casings",
      "Bathroom mineral deposit & grout scrub with antimicrobial steam",
      "Stovetop, range hood, and appliance exterior degreasing",
      "HEPA 4-stage microscopic dust & allergen filtration",
      "Sanitized door handles, electrical faceplates & vents",
    ],
    isActive: true,
  },
  {
    id: "srv-standard",
    slug: "standard-maintenance",
    title: "Standard Maintenance Clean",
    tagline: "Effortless, sparkling recurring upkeep",
    description: "Designed for regularly maintained homes. Full dusting, surface sanitation, HEPA vacuuming, hardwood mopping, kitchen disinfection, and complete bathroom sanitization.",
    estimatedHoursBase: 2.5,
    iconName: "Sparkles",
    badgeText: "Recurring Favorite",
    inclusions: [
      "All countertops, vanity basins & sinks sanitized",
      "Exterior of kitchen appliances polished to streak-free shine",
      "Beds made and linens fluffed",
      "Full vacuum and microfiber mop of all floors",
      "Trash emptied and cans sanitized",
    ],
    isActive: true,
  },
  {
    id: "srv-move",
    slug: "move-in-move-out",
    title: "Move-In / Move-Out Turnover",
    tagline: "100% Security deposit & realtor inspection standard",
    description: "Comprehensive empty home white-glove turnaround. Cleans inside all empty cabinets, drawers, closets, pantries, baseboards, and window tracks for spotless handoffs.",
    estimatedHoursBase: 5.0,
    iconName: "Home",
    badgeText: "Deposit Guaranteed",
    inclusions: [
      "Inside empty kitchen & bathroom cabinets, drawers & pantry",
      "Deep scrub of tubs, shower pans, glass, and basins",
      "Inside closet shelving, rods & floor vacuuming",
      "Baseboards, window sills, and blinds detailed",
      "Ready for immediate lease or sale photography",
    ],
    isActive: true,
  },
  {
    id: "srv-airbnb",
    slug: "airbnb-turnover",
    title: "Airbnb & Vacation Rental Prep",
    tagline: "5-Star guest review staging across Riverside",
    description: "Rapid hospitality turnaround. Includes linen laundry, fresh bed staging, restocking guest amenities, bathroom towel folding, high-touch sanitization, and photo inspection.",
    estimatedHoursBase: 3.0,
    iconName: "BedDouble",
    badgeText: "Superhost Partner",
    inclusions: [
      "Linen strip, wash, dry, and hotel-style bed staging",
      "Guest amenities & toiletries check and staging",
      "Trash removal and fresh liners installed",
      "Kitchenware washed, dried, and stored",
      "Completion photos sent to host immediately",
    ],
    isActive: true,
  },
  {
    id: "srv-urgent",
    slug: "urgent-same-day",
    title: "Urgent / Same-Day Clean",
    tagline: "Priority 2-hour response crew in Riverside",
    description: "Fast-dispatch emergency crew for last-minute house guests, post-party cleanups, sudden real estate viewings, or landlord inspections across Riverside zip codes.",
    estimatedHoursBase: 3.5,
    iconName: "Zap",
    badgeText: "Express Dispatch",
    inclusions: [
      "Guaranteed priority arrival window",
      "Multi-cleaner team deployed for rapid turnaround",
      "Focus on high-impact entertaining and guest areas",
      "Complete bathroom & kitchen fast-track disinfection",
    ],
    isActive: true,
  },
];

export const ADDONS_CATALOG: AddOnItem[] = [
  {
    id: "addon-oven",
    slug: "inside-oven",
    name: "Inside Oven Scour",
    description: "Deep carbon & grease degreasing with non-toxic, fume-free formulas",
    estimatedMinutes: 40,
    iconName: "Flame",
    badgeText: "Kitchen Detail",
    isActive: true,
  },
  {
    id: "addon-fridge",
    slug: "inside-fridge",
    name: "Inside Fridge & Freezer",
    description: "Shelves washed, sticky spills sanitized, interior walls deodorized",
    estimatedMinutes: 35,
    iconName: "Refrigerator",
    badgeText: "Fresh Interior",
    isActive: true,
  },
  {
    id: "addon-windows",
    slug: "interior-windows",
    name: "Interior Windows & Tracks",
    description: "Streak-free glass cleaning, window sill wiping, and vacuumed tracks",
    estimatedMinutes: 45,
    iconName: "Maximize2",
    badgeText: "Crystal Clear",
    isActive: true,
  },
  {
    id: "addon-pet-hair",
    slug: "pet-hair-detail",
    name: "Pet Hair Extraction Detail",
    description: "Specialized electrostatic roller & HEPA fur extraction for pet lovers",
    estimatedMinutes: 30,
    iconName: "Dog",
    badgeText: "Pet Lovers",
    isActive: true,
  },
  {
    id: "addon-baseboards",
    slug: "baseboards-doors",
    name: "Baseboards & Door Frames",
    description: "Individual hand-wiping of all moldings, baseboards, and interior doors",
    estimatedMinutes: 45,
    iconName: "Layers",
    badgeText: "Architectural",
    isActive: true,
  },
  {
    id: "addon-cabinets",
    slug: "inside-cabinets",
    name: "Inside Cabinets & Drawers",
    description: "Wipe down interior shelves and crumb vacuuming across kitchen & bath",
    estimatedMinutes: 40,
    iconName: "Archive",
    badgeText: "Storage Deep Clean",
    isActive: true,
  },
  {
    id: "addon-eco",
    slug: "eco-green-supplies",
    name: "100% Botanical Green Supplies",
    description: "Hypoallergenic, plant-based eucalyptus and citrus eco products",
    estimatedMinutes: 0,
    iconName: "Leaf",
    badgeText: "Non-Toxic",
    isActive: true,
  },
  {
    id: "addon-patio",
    slug: "patio-balcony",
    name: "Patio & Balcony Sweep/Wipe",
    description: "Outdoor patio furniture wiping, dust removal, and thorough sweep",
    estimatedMinutes: 25,
    iconName: "Sun",
    badgeText: "Outdoor Living",
    isActive: true,
  },
];

export const VERIFIED_GOOGLE_REVIEWS: ReviewItem[] = [
  {
    id: "rev-1",
    author: "Sarah Jenkins",
    rating: 5,
    date: "3 days ago",
    text: "MaidsMagic transformed our Canyon Crest home! We scheduled the Luxury Deep Clean before hosting family and our kitchen and bathrooms looked brand new. The crew was punctual, masked, and so polite. Truly a luxury experience.",
    neighborhood: "Canyon Crest, Riverside",
    serviceType: "Luxury Deep Clean",
    verifiedSourceUrl: "https://maps.google.com/?q=1405+Spruce+St,+Riverside,+CA+92507",
    avatarUrl: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80",
    isFeatured: true,
  },
  {
    id: "rev-2",
    author: "David Martinez",
    rating: 5,
    date: "1 week ago",
    text: "As a busy real estate agent in Riverside, I need dependable move-out cleaning. MaidsMagic handled three Orangecrest properties for me this month and every single tenant got their full security deposit back. 10/10 service!",
    neighborhood: "Orangecrest, Riverside",
    serviceType: "Move-In/Move-Out",
    verifiedSourceUrl: "https://maps.google.com/?q=1405+Spruce+St,+Riverside,+CA+92507",
    avatarUrl: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80",
    isFeatured: true,
  },
  {
    id: "rev-3",
    author: "Elena Rostova",
    rating: 5,
    date: "2 weeks ago",
    text: "We have two large golden retrievers and dog hair was everywhere. The Pet Hair Detail add-on was magical! Our Hawarden Hills home feels pristine and smells like fresh eucalyptus without harsh chemical fumes.",
    neighborhood: "Hawarden Hills, Riverside",
    serviceType: "Bi-Weekly Maintenance",
    verifiedSourceUrl: "https://maps.google.com/?q=1405+Spruce+St,+Riverside,+CA+92507",
    avatarUrl: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80",
    isFeatured: true,
  },
  {
    id: "rev-4",
    author: "Marcus Vance",
    rating: 5,
    date: "3 weeks ago",
    text: "I run 2 Airbnbs near UCR and Box Springs. MaidsMagic is my secret weapon. They stage towels beautifully, restock essentials, and notify me with photos the minute it is ready. Guests constantly compliment the cleanliness.",
    neighborhood: "UCR / Box Springs, Riverside",
    serviceType: "Airbnb Turnover Prep",
    verifiedSourceUrl: "https://maps.google.com/?q=1405+Spruce+St,+Riverside,+CA+92507",
    avatarUrl: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80",
    isFeatured: true,
  },
  {
    id: "rev-5",
    author: "Patricia & Robert Cole",
    rating: 5,
    date: "1 month ago",
    text: "Living in the historic Wood Streets neighborhood, our crown moldings and 1920s windows require gentle, attentive care. MaidsMagic treats our house with incredible respect. Bi-weekly client for 6 months now!",
    neighborhood: "Wood Streets, Riverside",
    serviceType: "Standard Maintenance",
    verifiedSourceUrl: "https://maps.google.com/?q=1405+Spruce+St,+Riverside,+CA+92507",
    avatarUrl: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80",
    isFeatured: true,
  },
  {
    id: "rev-6",
    author: "Dr. Raymond Chen",
    rating: 5,
    date: "1 month ago",
    text: "Called them at 8:30 AM for an urgent same-day clean in Victoria after our contractor finished tiling. A team of two arrived at 11:00 AM sharp with industrial HEPA vacuums. Impeccable work ethic and fair pricing.",
    neighborhood: "Victoria, Riverside",
    serviceType: "Urgent Same-Day Clean",
    verifiedSourceUrl: "https://maps.google.com/?q=1405+Spruce+St,+Riverside,+CA+92507",
    avatarUrl: "https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=150&auto=format&fit=crop&q=80",
    isFeatured: true,
  },
];

export const CLEANING_SPECIALISTS: CleanerSpecialist[] = [
  {
    id: "cl-1",
    fullName: "Maria Rodriguez",
    teamName: "Sapphire Elite Crew Lead",
    phone: "(951) 697-9001",
    email: "maria.r@maidsmagicriverside.com",
    avatarUrl: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80",
    rating: 4.98,
    completedJobs: 412,
    assignedZipCodes: ["92506", "92507", "92508"],
    specialty: "Luxury Estate Deep Cleans & Marble Care",
    isActive: true,
  },
  {
    id: "cl-2",
    fullName: "David Sterling",
    teamName: "Royal Standard Crew Lead",
    phone: "(951) 697-9002",
    email: "david.s@maidsmagicriverside.com",
    avatarUrl: "https://images.unsplash.com/photo-1560250097-0b93528c311a?w=150&auto=format&fit=crop&q=80",
    rating: 4.95,
    completedJobs: 320,
    assignedZipCodes: ["92501", "92503", "92504"],
    specialty: "Historic Wood Streets Craftsman & Deep Detailing",
    isActive: true,
  },
  {
    id: "cl-3",
    fullName: "Elena & Carlos Vasquez",
    teamName: "Turnover & Move-Out Duo",
    phone: "(951) 697-9003",
    email: "vasquez.team@maidsmagicriverside.com",
    avatarUrl: "https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150&auto=format&fit=crop&q=80",
    rating: 5.0,
    completedJobs: 580,
    assignedZipCodes: ["92506", "92501", "92508", "92507"],
    specialty: "100% Deposit Guarantee Move-Outs & Inspections",
    isActive: true,
  },
  {
    id: "cl-4",
    fullName: "Sofia Gutierrez",
    teamName: "Express & Hospitality Lead",
    phone: "(951) 697-9004",
    email: "sofia.g@maidsmagicriverside.com",
    avatarUrl: "https://images.unsplash.com/photo-1567532939604-b6b5b0db2604?w=150&auto=format&fit=crop&q=80",
    rating: 4.93,
    completedJobs: 245,
    assignedZipCodes: ["92504", "92505", "92503"],
    specialty: "Airbnb 5-Star Staging & Same-Day Dispatch",
    isActive: true,
  },
];

export const INITIAL_CUSTOMERS: CustomerProfile[] = [
  {
    id: "cust-1",
    name: "Eleanor Vance",
    phone: "(951) 342-8819",
    email: "eleanor.vance@gmail.com",
    address: "4820 Overlook Terrace, Riverside, CA 92506",
    neighborhood: "Canyon Crest",
    totalBookings: 14,
    frequency: "bi_weekly",
    preferredCleaner: "Maria Rodriguez",
    notes: "Requires gentle botanical solutions on master bath marble. Gate code #4492.",
    tags: ["VIP Riverside", "Recurring Client", "Keyless Entry"],
  },
  {
    id: "cust-2",
    name: "Gregory Miller",
    phone: "(951) 529-1044",
    email: "gmiller.realty@outlook.com",
    address: "1892 Citrus Grove Way, Riverside, CA 92508",
    neighborhood: "Orangecrest",
    totalBookings: 8,
    frequency: "one_time",
    preferredCleaner: "Elena & Carlos Vasquez",
    notes: "Commercial realtor partner. Needs itemized move-out checklists for deposit returns.",
    tags: ["Realtor Partner", "Move-Out Specialist"],
  },
  {
    id: "cust-3",
    name: "Dr. Amanda Wright",
    phone: "(951) 827-3920",
    email: "awright.md@ucrhealth.org",
    address: "3614 Mission Inn Ave, Riverside, CA 92501",
    neighborhood: "The Wood Streets",
    totalBookings: 22,
    frequency: "weekly",
    preferredCleaner: "David Sterling",
    notes: "Has 1 friendly golden retriever. Prefers Thursday morning arrivals.",
    tags: ["Weekly VIP", "Pet Friendly"],
  },
  {
    id: "cust-4",
    name: "Harrison Forde",
    phone: "(951) 488-6612",
    email: "h.forde@inlandempiremgmt.com",
    address: "1105 University Ave #204, Riverside, CA 92507",
    neighborhood: "UCR / Box Springs",
    totalBookings: 35,
    frequency: "bi_weekly",
    preferredCleaner: "Sofia Gutierrez",
    notes: "Superhost property manager. Requires towel folding origami and photo verification.",
    tags: ["Airbnb Host", "Priority Staging"],
  },
];
